[package]
name = "waterkit-test"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
clap = { version = "4", features = ["derive"] }
toml_edit = "0.23"
anyhow = "1.0"
owo-colors = "4.0"
